### ISSUE TITLE
Example docker compose setup

### ISSUE THREAD

**Issue by iTrooz** [MindFlavor/prometheus_wireguard_exporter#129]
Hey, for anyone looking for a simple docker compose setup, here is one:
```yml
services:
  wg-exporter:
    image: mindflavor/prometheus-wireguard-exporter
    network_mode: host
    command: -a true # See https://github.com/MindFlavor/prometheus_wireguard_exporter/issues/99
    user: root # To be able to read wireguard config file
    environment:
      - PROMETHEUS_WIREGUARD_EXPORTER_CONFIG_FILE_NAMES=/etc/wireguard/wg.conf
    expose:
      - "9586"
    volumes:
      - /etc/wireguard:/etc/wireguard:ro
    cap_add:
      - NET_ADMIN
```
