### ISSUE TITLE
What if wireguard is also running in docker

### ISSUE THREAD

**Issue by logopk** [MindFlavor/prometheus_wireguard_exporter#58]
My setup is running wireguard in a docker container managed with docker-compose

```yml
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    dns:
      - <mydns>
    dns_search: <mydomain>
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=mydomain #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=<mydns> #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - wireguard_data:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - default
 ...
```

Apparently the wg-interfaces are not available on the host, so your container isn't reading them.

Any suggestions how to fix this?

Peter
