### ISSUE TITLE
No Friendly Name scraped

### ISSUE THREAD

**Issue by MrDrache333** [MindFlavor/prometheus_wireguard_exporter#87]
No friendly Names are shown in the scraped metrics but configured as described in the ReadMe.
Ive also restarted the service and Docker-Container

Docker-compose:
```yaml
version: '3'
services:
  exporter:
    image: mindflavor/prometheus-wireguard-exporter:3.5.1
    restart: always
    network_mode: "host"
    volumes:
      - /etc/wireguard/wg0.conf:/etc/wireguard/wg0.conf
    cap_add:
      - NET_ADMIN
```
wg0.conf (1 client)
```
### begin keno ###
[Peer]
# friendly_name = Kenos iPhone
PublicKey = something
PresharedKey = something
AllowedIPs = 10.6.0.2/32
### end keno ###
```

Metrics:
```
# HELP wireguard_sent_bytes_total Bytes sent to the peer
# TYPE wireguard_sent_bytes_total counter
wireguard_sent_bytes_total{interface="wg0",public_key="something",allowed_ips="10.6.0.2/32"} 449223260

# HELP wireguard_received_bytes_total Bytes received from the peer
# TYPE wireguard_received_bytes_total counter
wireguard_received_bytes_total{interface="wg0",public_key="something",allowed_ips="10.6.0.2/32"} 76705376

# HELP wireguard_latest_handshake_seconds Seconds from the last handshake
# TYPE wireguard_latest_handshake_seconds gauge
wireguard_latest_handshake_seconds{interface="wg0",public_key="something",allowed_ips="10.6.0.2/32"} 1643142935
```
